### PR TITLE
Daniel to main

### PR DESCRIPTION
**Pull request by YoungMasterGandalf**
-- fix the UI bugs by reverting the problematic commit

### CODE REVIEW

**Comment by DovaX** [comment]
Please be more specific about what this PR solves?

**Comment by YoungMasterGandalf** [comment]
This PR solves (at least) two issues which appeared with the reverted commit:
- VariableExplorer labels didn't update position after resize so they could end up in the middle of workspace or elsewhere
- VariableExplorer popup (opened when you double-click on a variable in the variable explorer) drag breaks --> when you try to drag just the frame is dragged while the text and a grid stays in place

The issue here was that the refresh of UI was happening only when the data shape in the Table changed (df.shape) which is not happening in cases of pure FE changes (screen resize, window drag)

@DovaX

**Comment by DovaX** [comment]
Correct solution is to implement refresh of cells position + refresh of the labels inside of the table_cells - instead of reinitializing the whole cells by creating new ones

**Comment by DovaX** [comment]
I can't accept this PR since it brings back performance problems that were related to reinitializing the cells all the time. Please implement refresh of the current cells inside of forloop platform only and if the function will be meaninfgul we will generalize it to pgwidget

**Pull request closed without merging**
